# Generated by Django 3.1.5 on 2022-10-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=32)),
                ('firstName', models.CharField(max_length=32)),
                ('lastName', models.CharField(max_length=32)),
                ('PFP', models.ImageField(upload_to='pfp/')),
            ],
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='desc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='title',
            new_name='Title',
        ),
    ]
